version: '3.4'

services:
  carshop.web:
    image: ${DOCKER_REGISTRY-}carshopweb
    build:
      context: .
      dockerfile: CarShop.Web/Dockerfile

  carshop.carstorage:
    image: ${DOCKER_REGISTRY-}carshopcarstorage
    build:
      context: .
      dockerfile: CarShop.CarStorage/Dockerfile

  carshop.adminservice:
    image: ${DOCKER_REGISTRY-}carshopadminservice
    build:
      context: .
      dockerfile: CarShop.AdminService/Dockerfile

  db:
    image: postgres:17

